# -*- coding: utf-8 -*-
"""Soal Logic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14hNKReBI3LNnfMyhG9_4rSvTavVi5MLH

SOAL LOGIC NOMOR 1
"""

input_data = None (#Ubah input_data secara manual)

if input_data is None:
  print("0")
else:
  print("1")

"""SOAL LOGIC NOMOR 2"""

import string
alphabet = list(string.ascii_lowercase)

def cek_string(str_1):
    
    if str_1 in alphabet:
      print("0")
    else:
     print("1")


str_1 = input('Input String : ')
cek_string(str_1)

"""SOAL LOGIC NOMOR 3"""

input_huruf = input("Input Huruf Disini : ")

count = 0

for i in input_huruf:
  if (i in "aAeEiIoOuU"):
    count += 1

print("Total : ", count)

"""SOAL LOGIC NOMOR 5"""

import re

str1="@@HALOWORLD@@"
str2= "HALOWORLD"

check = re.compile('[@_!#$%^&*()<>?/\|}{:]')

if(check.search(str1) == None): #ganti str1 menjadi str 2 dan sebaliknya
  print("Tidak Mengandung Special Character")
else:
  print("Mengandung Special Character")

